#!/bin/sh
PLIST=/Library/LaunchDaemons/io.github.spark198rus.awg-hs.plist
mkdir -p /usr/local/bin
ln -sf "/Library/Application Support/AWG-HS/awg-hs" /usr/local/bin/awg-hs
launchctl bootstrap system "$PLIST" 2>/dev/null || launchctl load -w "$PLIST"
exit 0
